# List of stocks to ingest
targets_to_ingest:

# Banks
  - NUBR33.SA
  - ITUB4.SA
  - ABCB4.SA
  - RPAD5.SA
  - BRIV4.SA
  - BAZA3.SA
  - BMGB4.SA
  - BPAN4.SA
  - BGIP4.SA
  - BEES3.SA
  - BRSR6.SA
  - BBDC4.SA
  - BBAS3.SA
  - BSLI4.SA
  - BPAC11.SA
  - INBR32.SA
  - BMEB4.SA
  - BMIN4.SA
  - BNBR3.SA
  - SANB11.SA


  - RRRP3.SA
  - BPAC11.SA
  - ENEV3.SA
  - B3SA3.SA
  - PETR4.SA
  - ERJ
  - GOLL4.SA
  - EZTC3.SA
  - PETZ3.SA


data_prep:
  price_to_roc: False
  history_length: 21
  test_days: 180

model:
  hidden_size: 14
  horizon_forecast: 1
  epoch: 50