
ingest:
  # List of stocks to ingest
  target_stocks:

  # # TOP5 BANKS
    - ITUB4.SA # It is the largest private bank in Brazil and has a significant presence in various countries.
    - BBDC4.SA # Another major private-sector bank with a vast network of branches and services across the country.
    - BBAS3.SA # It is the largest public bank in Brazil and has a strong presence both domestically and internationally.
    - SANB11.SA # The Brazilian unit of the global banking group Santander, it has become one of the main banks in Brazil.
    - BPAC11.SA # It is a leading investment bank in Brazil and has expanded its retail banking operations in recent years.

  macro_indicators: 
    - Risco-Brasil
    - PIB
    - Dolar
    - Selic Over
    - IPCA

  fundamental_indicators:
    - P/L
    - PL/ATIVOS
    - M. EBIT
    - ROA
    - CAGR LUCROS 5 ANOS

data_prep:
  pe_t: 30
  history: 730
  min_points_history: 5
  horizon_forecast: 90
  test_days: 360
  start: 100
  step_every: 100

hyperparams:
  out_lstm_size: 50
  out_gnn_size: 50
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.01
  scheduler: "ReduceLROnPlateau"
  patience: 50
  patience_stop: 400
  factor: 0.8
  epochs: 2000
  pct_subset: 1
  use_gnn: True

  