
ingest:
  # List of stocks to ingest
  target_stocks:

  # TOP5 BANKS
    - ITUB4.SA # It is the largest private bank in Brazil and has a significant presence in various countries.
    - BBDC4.SA # Another major private-sector bank with a vast network of branches and services across the country.
    - BBAS3.SA # It is the largest public bank in Brazil and has a strong presence both domestically and internationally.
    - SANB11.SA # The Brazilian unit of the global banking group Santander, it has become one of the main banks in Brazil.
    - BPAC11.SA # It is a leading investment bank in Brazil and has expanded its retail banking operations in recent years.

  # TOP5 RANDOM
    # - PETR4.SA # Energy Sector - Petrobras is Brazil's state-controlled oil company and is a major player in the exploration, production, and refining of oil and natural gas.
    # - VALE3.SA # Mining Sector - Vale is one of the world's largest producers of iron ore and nickel. They also produce copper, coal, manganese, and other minerals.
    # - ABEV3.SA # Beverage Sector - AmBev, or Companhia de Bebidas das Américas, is a major beverage company known for its beers, soft drinks, and other beverages. Brands under its umbrella include Skol, Brahma, and Antarctica.
    # - B3SA3.SA # Financial Services Sector - B3 is the main financial market infrastructure company in Brazil and offers services related to exchange markets, over-the-counter markets, and infrastructure for the issuance of financial assets.
    # - JBSS3.SA # Food Sector - JBS is one of the world's leading food industry companies with a vast portfolio that includes meat, poultry, lamb, and leather processing.

  macro_indicators:
    Risco-Brasil: 'JPM366_EMBI366'
    PIB: 'BM12_PIB12'
    Dolar: 'BM12_ERC12'
    Selic Over: 'BM12_TJOVER12'
    IPCA: 'PRECOS12_IPCAG12'

  fundamental_indicators:
    - P/L
    - PL/ATIVOS
    - M. EBIT
    - ROA
    - CAGR LUCROS 5 ANOS

data_prep:
  pe_t: 10
  history: 31
  horizon_forecast: 14
  test_days: 180
  step_every: 100

hyperparams:
  out_lstm_size: 5
  out_gnn_size: 5
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.01
  scheduler: "ReduceLROnPlateau"
  patience: 8
  factor: 0.8
  epochs: 300
  use_gnn: True
  