
ingest:
  # List of stocks to ingest
  target_stocks:
    # - BAZA3.SA
    # - BEES3.SA
    # - BMEB4.SA
    # - BBAS3.SA
    # - BMIN4.SA
    - BGIP4.SA
    - ABCB4.SA
  macro_indicators: 
    - Risco-Brasil
    - PIB
    - Dolar
    - Selic Over
    - IPCA

  fundamental_indicators:
    - P/L
    - PL/ATIVOS
    - M. EBIT
    - ROA
    - CAGR LUCROS 5 ANOS

data_prep:
  pe_t: 30
  history: 730
  min_points_history: 5
  horizon_forecast: 90
  test_days: 360
  start: 60
  step_every: 200

hyperparams:
  out_lstm_size: 50
  out_gnn_size: 50
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.01
  scheduler: "ReduceLROnPlateau"
  patience: 50
  patience_stop: 400
  factor: 0.8
  epochs: 2000
  pct_subset: 1
  use_gnn: True

  