# List of stocks to ingest
targets_to_ingest:
  - RRRP3.SA
  - BPAC11.SA
  - ENEV3.SA
  - B3SA3.SA
  - PETR4.SA
  - ERJ
  - GOLL4.SA
  - EZTC3.SA
  - PETZ3.SA


data_prep:
  history_length: 14
  test_days: 180

model:
  hidden_size: 8
  horizon_forecast: 1
  epoch: 2