# List of stocks to ingest
targets_to_ingest:

# Banks
  - NUBR33.SA
  - ITUB4.SA
  - ABCB4.SA
  - RPAD5.SA
  - BRIV4.SA
  - BAZA3.SA
  - BMGB4.SA
  - BPAN4.SA
  - BGIP4.SA
  - BEES3.SA
  - BRSR6.SA
  - BBDC4.SA
  - BBAS3.SA
  - BSLI4.SA
  - BPAC11.SA
  - INBR32.SA
  - BMEB4.SA
  - BMIN4.SA
  - BNBR3.SA
  - SANB11.SA


  - RRRP3.SA
  - BPAC11.SA
  - ENEV3.SA
  - B3SA3.SA
  - PETR4.SA
  - ERJ
  - GOLL4.SA
  - EZTC3.SA
  - PETZ3.SA


data_prep:
  corr: "spearman"
  min_periods: 31
  history_length: 14 # CHANGE BOTH !!!!!
  test_days: 180

model:
  history_length: 14 # CHANGE BOTH !!!!!
  hidden_size: 7
  output_enc: 7
  horizon_forecast: 1
  dropout: 0.2
  epoch: 100
  lr_adam: 0.01
  factor: 0.1
  shuffle: True
  