# List of stocks to ingest
targets_to_ingest:
  - RRRP3.SA
  - BPAC11.SA
  - ENEV3.SA
  - B3SA3.SA
  - PETR4.SA
  - ERJ
  - GOLL4.SA
  - EZTC3.SA
  - PETZ3.SA
  - ITUB4.SA
  - BBDC4.SA


data_prep:
  price_to_roc: False
  history_length: 21
  test_days: 180

model:
  hidden_size: 14
  horizon_forecast: 1
  epoch: 60