
ingest:
  # List of stocks to ingest
  target_stocks:
    # - BAZA3.SA
    # - BEES3.SA
    # - BMEB4.SA
    # - BBAS3.SA
    # - BMIN4.SA
    - BGIP4.SA
    - ABCB4.SA
  macro_indicators: 
    - Risco-Brasil
    - PIB
    - Dolar
    - Selic Over
    - IPCA

  fundamental_indicators:
    - P/L
    - PL/ATIVOS
    - M. EBIT
    - ROA
    - CAGR LUCROS 5 ANOS

data_prep:
  pe_t: 10
  history: 120
  min_points_history: 1
  horizon_forecast: 14
  test_days: 360
  start: 60
  step_every: 100

hyperparams:
  out_lstm_size: 50
  out_gnn_size: 50
  criterion: "IoA" # "MAPE" "IoA"
  optimizer: "Adam"
  lr: 0.01
  scheduler: "ReduceLROnPlateau"
  patience: 15
  patience_stop: 100
  factor: 0.9
  epochs: 1000
  pct_subset: 1
  dropout_gnn: 0
  heads: 8
  concat: False #True Not implemented
  use_gnn: False

  