version: '3.8'
services:
  myservice:
    build: .
    runtime: nvidia  # This line is crucial
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # This line ensures that all NVIDIA devices are visible inside the container
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8501:8501" # Exposes Streamlit's default port 8501
